### ISSUE TITLE
Understanding difference of loaders

### ISSUE THREAD

**Issue by KIVagant** [pinepain/php-simple-config#1]
What difference between Cached and Merged loaders? Should and can I use both of them if I need a dynamic calculus? Inside code I see critical difference, CachedLoader uses var_export, but MergedLoader is not.

**Comment by pinepain** [comment]
Cached loader dump config items as is (after config files `require`d, for example, in fact it is configs source-agnostic) when Merged loader merge config files into one and heavy depends on FilesLoader loader. I've added section to readme to cover the difference between loaders.
